# Generated by Django 4.2.13 on 2024-08-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='license',
            field=models.ImageField(blank=True, null=True, upload_to='business_documents/'),
        ),
    ]
