# Generated by Django 4.2.13 on 2024-08-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_vendor_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='license',
            field=models.ImageField(null=True, upload_to='business_documents/'),
        ),
    ]
